/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.enrollmentsystem;

import javax.swing.*;
import java.sql.*;

/**
 *
 * @author bhilario
 */
public class LoginForm extends javax.swing.JFrame {
    
    EnrollmentSystem b = new EnrollmentSystem();
    private boolean isLoggedIn = false;
    String loginUserADDED, loginPassADDED;
    
    private void messagebox(String msg, String titlebar){
     JOptionPane.showMessageDialog(null,msg,titlebar,JOptionPane.INFORMATION_MESSAGE);   
     } 
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginForm.class.getName());
    
    public LoginForm() {
    initComponents();

    schoolyearbox.removeAllItems();
    schoolyearbox.addItem("-- Select Database --");
}
    private void loadDatabasesForUser(String user, String pass) {
    schoolyearbox.removeAllItems();
    schoolyearbox.addItem("-- Select Database --");
    
    // Root can see all enrollment databases
    if (user.equalsIgnoreCase("root")) {
        try (Connection c = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC", user, pass); 
             Statement s = c.createStatement(); 
             ResultSet r = s.executeQuery("SHOW DATABASES")) {
            
            while (r.next()) { 
                String dbName = r.getString(1); 
                if (dbName.startsWith("enrollment_")) {
                    schoolyearbox.addItem(dbName);
                }
            } 
        } catch (Exception ex) { 
            System.out.println("Error loading databases for admin: " + ex.getMessage()); 
        }
        return;
    }

    // For Student / Teacher users: query databases to check if user exists in students or teachers table
    try (Connection c = DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC", "root", "root"); 
         Statement s = c.createStatement(); 
         ResultSet r = s.executeQuery("SHOW DATABASES")) {
        
        while (r.next()) { 
            String dbName = r.getString(1); 
            if (dbName.startsWith("enrollment_")) {
                boolean isRegisteredInDb = false;

                // Check if student exists in this database
                try (Statement dbStmt = c.createStatement();
                     ResultSet studRs = dbStmt.executeQuery("SELECT studid, studname FROM `" + dbName + "`.students")) {
                    while (studRs.next()) {
                        String studentAccount = studRs.getInt(1) + studRs.getString(2).replaceAll("\\s+", "").toLowerCase();
                        if (studentAccount.equalsIgnoreCase(user)) {
                            isRegisteredInDb = true;
                            break;
                        }
                    }
                } catch (Exception ignored) {}

                // Check if teacher exists in this database
                if (!isRegisteredInDb) {
                    try (Statement dbStmt = c.createStatement();
                         ResultSet teachRs = dbStmt.executeQuery("SELECT tid, tname FROM `" + dbName + "`.teachers")) {
                        while (teachRs.next()) {
                            String teacherAccount = teachRs.getInt(1) + teachRs.getString(2).replaceAll("\\s+", "").toLowerCase();
                            if (teacherAccount.equalsIgnoreCase(user)) {
                                isRegisteredInDb = true;
                                break;
                            }
                        }
                    } catch (Exception ignored) {}
                }

                // Only display database if user is enrolled/registered in it
                if (isRegisteredInDb) {
                    schoolyearbox.addItem(dbName);
                }
            }
        } 
    } catch (Exception ex) { 
        System.out.println("Error loading databases for user: " + ex.getMessage()); 
    } 
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        passwordfield = new javax.swing.JPasswordField();
        usernamefield = new javax.swing.JTextField();
        Loginbutton = new javax.swing.JButton();
        schoolyearbox = new javax.swing.JComboBox<>();
        submitbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("User Login");

        passwordfield.addActionListener(this::passwordfieldActionPerformed);

        usernamefield.addActionListener(this::usernamefieldActionPerformed);

        Loginbutton.setText("Login");
        Loginbutton.addActionListener(this::LoginbuttonActionPerformed);

        schoolyearbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        schoolyearbox.addActionListener(this::schoolyearboxActionPerformed);

        submitbutton.setText("Submit");
        submitbutton.addActionListener(this::submitbuttonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(passwordfield)
                            .addComponent(usernamefield, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(schoolyearbox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(Loginbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(submitbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(182, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(51, 51, 51)
                .addComponent(usernamefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(passwordfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Loginbutton)
                .addGap(37, 37, 37)
                .addComponent(schoolyearbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(submitbutton)
                .addGap(115, 115, 115))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbuttonActionPerformed
        // TODO add your handling code here:
        if (!isLoggedIn) {
            messagebox("Access Denied: Please enter valid credentials and click Login first.", "ERROR");
            return;
        }

        Object selected = schoolyearbox.getSelectedItem();
        if (selected == null || selected.toString().equals("-- Select Database --")) {
            messagebox("Please select a valid database from the dropdown list.", "ERROR");
            return;
        }

        String mydb = selected.toString();
        b.currentDB(mydb);

        // ADDED: Role detector using database connection
        if (!loginUserADDED.equalsIgnoreCase("root")) { 
            EnrollmentSystem.userRole = "STUDENT"; 
            try (Connection tc = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/" + mydb + "?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC", loginUserADDED, loginPassADDED); 
                 Statement ts = tc.createStatement(); 
                 ResultSet tr = ts.executeQuery("SELECT tid, tname FROM teachers")) { 
                
                while (tr.next()) { 
                    if ((tr.getString(1) + tr.getString(2)).replaceAll("\\s+", "").equalsIgnoreCase(loginUserADDED)) {
                        EnrollmentSystem.userRole = "TEACHER"; 
                    }
                }
            } catch (Exception e) { 
                // Default to STUDENT role if teacher check fails
            } 
        } else {
            EnrollmentSystem.userRole = "ADMIN";
        }

        StudentsForm sf = new StudentsForm();
        sf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_submitbuttonActionPerformed

    private void LoginbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginbuttonActionPerformed
        // TODO add your handling code here:
        String user = usernamefield.getText().trim();
        String pass = new String(passwordfield.getPassword()).trim();
        
       
        if (user.isEmpty() || pass.isEmpty()) { 
            messagebox("Please enter username and password.", "ERROR");
            return; 
        } 
        

       
        try (Connection uc = DriverManager.getConnection( 
                "jdbc:mysql://localhost:3306/?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC", user, pass)) { // ADDED
            
            loginUserADDED = user; 
            loginPassADDED = pass; 
            isLoggedIn = true; 
            
          
            loadDatabasesForUser(user, pass); 
            messagebox("Login Successful! Select a database and click Submit.", "Success"); // ADDED
            
        } catch (SQLException ex) {
            isLoggedIn = false;
            schoolyearbox.removeAllItems();
            schoolyearbox.addItem("-- Select Database --");
            messagebox("Invalid username or password.", "ERROR");
        } 
    
    }//GEN-LAST:event_LoginbuttonActionPerformed

    private void usernamefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernamefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernamefieldActionPerformed

    private void passwordfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordfieldActionPerformed

    private void schoolyearboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schoolyearboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_schoolyearboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Loginbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField passwordfield;
    private javax.swing.JComboBox<String> schoolyearbox;
    private javax.swing.JButton submitbutton;
    private javax.swing.JTextField usernamefield;
    // End of variables declaration//GEN-END:variables
}
