package com.mycompany.enrollmentsystem;

import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author bhilario
 */
public class StudentsForm extends javax.swing.JFrame {
String stdid;
String sname;
String sadd;
String scourse;
String sgender;
String syrlvl;
String selectedEnrolledSubjId;

    public void showRecords(){
    DefaultTableModel tblmodel = (DefaultTableModel) studTable.getModel();
    tblmodel.setRowCount(0);
    EnrollmentSystem b = new EnrollmentSystem();
    b.DBConnect();
    
    String searchText = search.getText().trim();
    if (searchText.equals("Search")) {
        searchText = "";
    }
    
    try{
        String query = "select * from students where concat(studid, studname, studadd, studcrs, studgender, yrlvl) like ?";
        java.sql.PreparedStatement ps = b.con.prepareStatement(query);
        ps.setString(1, "%" + searchText + "%");
        b.rs = ps.executeQuery();
        System.out.println("Success with sql!");  
        
        while (b.rs.next()){
            String i = b.rs.getString("studid");
            String c = b.rs.getString("studname");
            String d = b.rs.getString("studadd");
            String t = b.rs.getString("studcrs");
            String g = b.rs.getString("studgender");
            String y = b.rs.getString("yrlvl");
            String[] items = {i,c,d,t,g,y};
            tblmodel.addRow(items);
        }
    }catch (Exception ex){
        System.out.print("not Success with sql!");
         ex.printStackTrace();
    }
}
    
    private void clearFields() {
    studid.setText("");
    studname.setText("");
    studadd.setText("");
    studcrs.setText("");
    studgender.setText("");
    yrlvl.setText("");
    showRecords();
}
    public void showEnrolledSubjects(int studid) {
    DefaultTableModel tblmodel = (DefaultTableModel) subjTable.getModel();
    tblmodel.setRowCount(0);

    enrolled e = new enrolled();
    for (String[] row : e.subjectsOfStudent(studid)) {
        tblmodel.addRow(row);
    }
}
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StudentsForm.class.getName());

    /**
     * Creates new form StudentsForm
     */
    public StudentsForm() {
        initComponents();
        studid.setEditable(false);
        if (EnrollmentSystem.userRole.equals("STUDENT")) { saveBtn.setEnabled(false); editBtn.setEnabled(false); deleteBtn.setEnabled(false); Enrollbutton.setEnabled(false); Dropbutton.setEnabled(false); databaseMenu.setEnabled(false); } 
        if (EnrollmentSystem.userRole.equals("TEACHER")) { deleteBtn.setEnabled(false); } 
        
        if (EnrollmentSystem.userRole.equals("STUDENT")){
            saveBtn.setEnabled(false);
            editBtn.setEnabled(false);
            deleteBtn.setEnabled(false);
        }
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        subjTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        yrlvl = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        studid = new javax.swing.JTextField();
        studname = new javax.swing.JTextField();
        studadd = new javax.swing.JTextField();
        studcrs = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        studgender = new javax.swing.JTextField();
        search = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        deleteBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        studTable = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        Enrollbutton = new javax.swing.JButton();
        Dropbutton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        databaseMenu = new javax.swing.JMenu();
        create1stsem = new javax.swing.JMenuItem();
        create2ndsem = new javax.swing.JMenuItem();
        createSummer = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        subjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "SubjID", "SubjCode", "SubjDesc", "SubjUnits", "SubjDesc"
            }
        ));
        subjTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                subjTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(subjTable);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel1.setText("STUDENT INFORMATION SYSTEM");

        jLabel2.setText("ID");

        jLabel3.setText("Name");

        jLabel4.setText("Address");

        jLabel5.setText("Course");

        jLabel6.setText("Gender");

        studid.addActionListener(this::studidActionPerformed);

        studname.addActionListener(this::studnameActionPerformed);

        jLabel7.setText("Year Level");

        search.setText("Search");
        search.setToolTipText("");
        search.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchFocusLost(evt);
            }
        });
        search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchMouseClicked(evt);
            }
        });
        search.addActionListener(this::searchActionPerformed);
        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchKeyPressed(evt);
            }
        });

        deleteBtn.setText("Delete");
        deleteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                deleteBtnMousePressed(evt);
            }
        });

        saveBtn.setText("Save");
        saveBtn.addActionListener(this::saveBtnActionPerformed);

        editBtn.setText("Edit");
        editBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editBtnMouseClicked(evt);
            }
        });
        editBtn.addActionListener(this::editBtnActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(deleteBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saveBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editBtn)
                .addGap(46, 46, 46))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn)
                    .addComponent(deleteBtn)
                    .addComponent(editBtn)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(studid, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(studname, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(studadd, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(studcrs, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(studgender, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(yrlvl, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(15, 15, 15))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(search)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studadd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studcrs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studgender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yrlvl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        studTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Address", "Course", "Gender", "Year Level"
            }
        ));
        studTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(studTable);

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel9.setText("Enrolled Subjects");

        Enrollbutton.setText("Enroll");
        Enrollbutton.addActionListener(this::EnrollbuttonActionPerformed);

        Dropbutton.setText("Drop");
        Dropbutton.addActionListener(this::DropbuttonActionPerformed);

        jMenu1.setText("Open");

        jMenuItem1.setText("Teachers");
        jMenuItem1.addActionListener(this::jMenuItem1ActionPerformed);
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Subjects");
        jMenuItem2.addActionListener(this::jMenuItem2ActionPerformed);
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        databaseMenu.setText("DataBase");

        create1stsem.setText("1st Semester");
        create1stsem.addActionListener(this::create1stsemActionPerformed);
        databaseMenu.add(create1stsem);

        create2ndsem.setText("2nd Semester");
        create2ndsem.addActionListener(this::create2ndsemActionPerformed);
        databaseMenu.add(create2ndsem);

        createSummer.setText("Summer");
        createSummer.addActionListener(this::createSummerActionPerformed);
        databaseMenu.add(createSummer);

        jMenuBar1.add(databaseMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Enrollbutton)
                                    .addComponent(Dropbutton)))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Enrollbutton)
                                .addGap(18, 18, 18)
                                .addComponent(Dropbutton)
                                .addGap(125, 125, 125))))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void searchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyPressed
        showRecords();
    }//GEN-LAST:event_searchKeyPressed

    private void searchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchFocusGained
        if (search.getText().equals("Search")) {
        search.setText("");
    }
        clearFields();
    }//GEN-LAST:event_searchFocusGained

    private void searchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchFocusLost
        if (search.getText().trim().isEmpty()) {
        search.setText("Search");
        }
    }//GEN-LAST:event_searchFocusLost

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
  Students c = new Students();
  
   int newId = c.newstudent(
    studname.getText(),
    studadd.getText(),
    studcrs.getText(),
    studgender.getText(),
    yrlvl.getText()
);
   if (newId > 0) {
    studid.setText(String.valueOf(newId));
}
   showRecords();
   clearFields();
    }//GEN-LAST:event_saveBtnActionPerformed

    private void studnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studnameActionPerformed

    private void studidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studidActionPerformed

    private void deleteBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBtnMousePressed
        Students b = new Students();
        b.delete_student(Integer.parseInt(studid.getText()));
        
        showRecords();

    }//GEN-LAST:event_deleteBtnMousePressed

    private void subjTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subjTableMouseClicked
       int selectedRow = subjTable.getSelectedRow();

   if (selectedRow < 0) return;

   selectedEnrolledSubjId = (String) subjTable.getValueAt(selectedRow, 0);
    }//GEN-LAST:event_subjTableMouseClicked

    private void editBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editBtnMouseClicked
        
  Students c = new Students();
  
   c.edit_student(
    Integer.parseInt(studid.getText()),
    studname.getText(),
    studadd.getText(),
    studcrs.getText(),
    studgender.getText(),
    yrlvl.getText()
    );
   showRecords();
             
    }//GEN-LAST:event_editBtnMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        TeachersForm tf = new TeachersForm();
        tf.setVisible(true);
        tf.showRecords();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
         if (SubjectsForm.instance == null || !SubjectsForm.instance.isDisplayable()) {
        SubjectsForm.instance = new SubjectsForm();
    }
    SubjectsForm.instance.setVisible(true);
    SubjectsForm.instance.showRecords();
    SubjectsForm.instance.toFront();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_searchMouseClicked

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editBtnActionPerformed

    private void studTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studTableMouseClicked
        // TODO add your handling code here:
        int selectedRow = studTable.getSelectedRow();

    if (selectedRow < 0) return;

    stdid = (String) studTable.getValueAt(selectedRow, 0);
    studid.setText(stdid);

    sname = (String) studTable.getValueAt(selectedRow, 1);
    studname.setText(sname);

    sadd = (String) studTable.getValueAt(selectedRow, 2);
    studadd.setText(sadd);

    scourse = (String) studTable.getValueAt(selectedRow, 3);
    studcrs.setText(scourse);

    sgender = (String) studTable.getValueAt(selectedRow, 4);
    studgender.setText(sgender);

    syrlvl = (String) studTable.getValueAt(selectedRow, 5);
    yrlvl.setText(syrlvl);

   selectedEnrolledSubjId = null;
    showEnrolledSubjects(Integer.parseInt(stdid));

    }//GEN-LAST:event_studTableMouseClicked

    private void EnrollbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnrollbuttonActionPerformed
        // TODO add your handling code here:
           if (stdid == null || stdid.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Select a student first.");
        return;
    }
    if (SubjectsForm.selectedSubjId == null || SubjectsForm.selectedSubjId.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Open the Subjects window and select a subject first.");
        return;
    }

    int confirm = javax.swing.JOptionPane.showConfirmDialog(
        this,
        "Enroll Student ID:" + stdid + " to Subject ID:" + SubjectsForm.selectedSubjId,
        "Confirm Enrollment",
        javax.swing.JOptionPane.OK_CANCEL_OPTION,
        javax.swing.JOptionPane.QUESTION_MESSAGE
    );
    if (confirm != javax.swing.JOptionPane.OK_OPTION) {
        return;
    }

    enrolled e = new enrolled();
    boolean ok = e.enroll_subject(Integer.parseInt(stdid), Integer.parseInt(SubjectsForm.selectedSubjId));
    if (!ok) {
        javax.swing.JOptionPane.showMessageDialog(this, "Student is already enrolled in that subject.");
    }
    showEnrolledSubjects(Integer.parseInt(stdid));
    if (SubjectsForm.instance != null) {
        SubjectsForm.instance.showClassList(Integer.parseInt(SubjectsForm.selectedSubjId));
     }
    }//GEN-LAST:event_EnrollbuttonActionPerformed

    private void DropbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DropbuttonActionPerformed
        // TODO add your handling code here:
           if (stdid == null || stdid.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Select a student first.");
        return;
    }
    if (selectedEnrolledSubjId == null || selectedEnrolledSubjId.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Select a subject from the Enrolled Subjects list first.");
        return;
    }

    int confirm = javax.swing.JOptionPane.showConfirmDialog(
        this,
        "Drop Student ID:" + stdid + " from Subject ID:" + selectedEnrolledSubjId,
        "Confirm Drop",
        javax.swing.JOptionPane.OK_CANCEL_OPTION,
        javax.swing.JOptionPane.QUESTION_MESSAGE
    );
    if (confirm != javax.swing.JOptionPane.OK_OPTION) {
        return;
    }

    enrolled e = new enrolled();
    e.drop_subject(Integer.parseInt(stdid), Integer.parseInt(selectedEnrolledSubjId));
    showEnrolledSubjects(Integer.parseInt(stdid));
    if (SubjectsForm.instance != null) {
        SubjectsForm.instance.showClassList(Integer.parseInt(selectedEnrolledSubjId));
     }
    }//GEN-LAST:event_DropbuttonActionPerformed

    private void createSummerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createSummerActionPerformed
        // TODO add your handling code here:
        EnrollmentSystem.createSemesterDatabase("summer");
    }//GEN-LAST:event_createSummerActionPerformed

    private void create1stsemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create1stsemActionPerformed
        // TODO add your handling code here:
        EnrollmentSystem.createSemesterDatabase("1stsem");
    }//GEN-LAST:event_create1stsemActionPerformed

    private void create2ndsemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create2ndsemActionPerformed
        // TODO add your handling code here:
        EnrollmentSystem.createSemesterDatabase("2ndsem");
    }//GEN-LAST:event_create2ndsemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new StudentsForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Dropbutton;
    private javax.swing.JButton Enrollbutton;
    private javax.swing.JMenuItem create1stsem;
    private javax.swing.JMenuItem create2ndsem;
    private javax.swing.JMenuItem createSummer;
    private javax.swing.JMenu databaseMenu;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextField search;
    private javax.swing.JTable studTable;
    private javax.swing.JTextField studadd;
    private javax.swing.JTextField studcrs;
    private javax.swing.JTextField studgender;
    private javax.swing.JTextField studid;
    private javax.swing.JTextField studname;
    private javax.swing.JTable subjTable;
    private javax.swing.JTextField yrlvl;
    // End of variables declaration//GEN-END:variables
}
