/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.enrollmentsystem;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bhilario
 */
public class TeachersForm extends javax.swing.JFrame {
    String tname;
    String tid;
    String tadd;
    String tdept;
    String tcontact;
    String tstatus;
    String selectedAssignedSubjId; 
    
            public void showRecords(){
    DefaultTableModel tblmodel = (DefaultTableModel) teachTable2.getModel();
    tblmodel.setRowCount(0);
    EnrollmentSystem b = new EnrollmentSystem();
    b.DBConnect();
    
    String searchText = search.getText().trim();
    if (searchText.equals("Search")) {
        searchText = "";
    }
    
    try{
    String query = "select * from teachers where concat(tid, tname, tadd, tdept, tcontact, tstatus) like ?";
    java.sql.PreparedStatement ps = b.con.prepareStatement(query);
    ps.setString(1, "%" + searchText + "%");
    b.rs = ps.executeQuery();
    System.out.println("Success with sql!");  
    
    while (b.rs.next()){
        String i = b.rs.getString("tid");
        String c = b.rs.getString("tname");
        String a = b.rs.getString("tadd");
        String d = b.rs.getString("tdept");
        String t = b.rs.getString("tcontact");
        String g = b.rs.getString("tstatus");
        String[] items = {i,c,a,d,t,g};
        tblmodel.addRow(items);
    }
}catch (Exception ex){
        System.out.print("not Success with sql!");
         ex.printStackTrace();
    }
}
public void showAssignedSubjects(int tid) {
    DefaultTableModel tblmodel = (DefaultTableModel) assignTable.getModel();
    tblmodel.setRowCount(0);

    Assign a = new Assign();
    for (String[] row : a.subjectsOfTeacher(tid)) {
        tblmodel.addRow(row);
    }
}
private void clearFields() {
    teachid.setText("");
    teachname.setText("");
    teachadd.setText("");
    teachdept.setText("");
    teachcontact.setText("");
    teachstatus.setText("");
}
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TeachersForm.class.getName());

    /**
     * Creates new form TeachersForm
     */
    public TeachersForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        teachTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        teachstatus = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        teachid = new javax.swing.JTextField();
        teachname = new javax.swing.JTextField();
        teachadd = new javax.swing.JTextField();
        teachdept = new javax.swing.JTextField();
        teachcontact = new javax.swing.JTextField();
        search = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        deleteBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        assignTable = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        teachTable2 = new javax.swing.JTable();
        Assignbutton = new javax.swing.JButton();
        deletebutton = new javax.swing.JButton();
        assignlabelt = new javax.swing.JLabel();

        teachTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Address", "Department", "Contact", "Status"
            }
        ));
        teachTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                teachTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(teachTable);
        if (teachTable.getColumnModel().getColumnCount() > 0) {
            teachTable.getColumnModel().getColumn(5).setHeaderValue("Status");
        }

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Teacher ID");

        jLabel3.setText("Name");

        jLabel4.setText("Address");

        jLabel5.setText("Department");

        jLabel6.setText("Contact");

        teachid.addActionListener(this::teachidActionPerformed);

        teachname.addActionListener(this::teachnameActionPerformed);

        search.setText("Search");
        search.setToolTipText("");
        search.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchFocusLost(evt);
            }
        });
        search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchMouseClicked(evt);
            }
        });
        search.addActionListener(this::searchActionPerformed);
        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchKeyPressed(evt);
            }
        });

        deleteBtn.setText("Delete");
        deleteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                deleteBtnMousePressed(evt);
            }
        });

        saveBtn.setText("Save");
        saveBtn.addActionListener(this::saveBtnActionPerformed);

        editBtn.setText("Edit");
        editBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(deleteBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saveBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editBtn)
                .addGap(46, 46, 46))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn)
                    .addComponent(deleteBtn)
                    .addComponent(editBtn)))
        );

        jLabel7.setText("Status");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(teachid, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(teachname, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(teachadd, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(teachdept, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(teachcontact, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(teachstatus, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(15, 15, 15))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(search)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teachid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teachname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teachadd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teachdept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teachcontact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teachstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jLabel1.setText("TEACHERS REGISTRATION SYSTEM");

        assignTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Subj ID", "Subj Code", "Subj Desc", "Subj Units", "Subj Sched"
            }
        ));
        assignTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                assignTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(assignTable);

        teachTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Address", "Department", "Contact", "Status"
            }
        ));
        teachTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                teachTable2MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(teachTable2);
        if (teachTable2.getColumnModel().getColumnCount() > 0) {
            teachTable2.getColumnModel().getColumn(5).setHeaderValue("Status");
        }

        Assignbutton.setText("Assign");
        Assignbutton.addActionListener(this::AssignbuttonActionPerformed);

        deletebutton.setText("Delete");
        deletebutton.addActionListener(this::deletebuttonActionPerformed);

        assignlabelt.setText("Assign Subject");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Assignbutton)
                            .addComponent(deletebutton)))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(assignlabelt, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(Assignbutton)
                                .addGap(18, 18, 18)
                                .addComponent(deletebutton)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(assignlabelt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38))))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void teachTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teachTableMouseClicked
        int selectedRow = teachTable.getSelectedRow();

        if (selectedRow < 0) return;

        tid = (String) teachTable.getValueAt(selectedRow, 0);
        teachid.setText(tid);

        tname = (String) teachTable.getValueAt(selectedRow, 1);
        teachname.setText(tname);

        tadd = (String) teachTable.getValueAt(selectedRow, 2);
        teachadd.setText(tadd);

        tdept = (String) teachTable.getValueAt(selectedRow, 3);
        teachdept.setText(tdept);

        tcontact = (String) teachTable.getValueAt(selectedRow, 4);
        teachcontact.setText(tcontact);

        tstatus = (String) teachTable.getValueAt(selectedRow, 5);
        teachstatus.setText(tstatus);
    }//GEN-LAST:event_teachTableMouseClicked

    private void teachidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teachidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teachidActionPerformed

    private void teachnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teachnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teachnameActionPerformed

    private void searchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchFocusGained
        if (search.getText().equals("Search")) {
            search.setText("");
        }
        clearFields();
    }//GEN-LAST:event_searchFocusGained

    private void searchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchFocusLost
        if (search.getText().trim().isEmpty()) {
            search.setText("Search");
        }
    }//GEN-LAST:event_searchFocusLost

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void searchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyPressed
        showRecords();
    }//GEN-LAST:event_searchKeyPressed

    private void deleteBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBtnMousePressed
        Teachers b = new Teachers();
        b.delete_teacher(Integer.parseInt(teachid.getText()));

        showRecords();
    }//GEN-LAST:event_deleteBtnMousePressed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        Teachers c = new Teachers();

        c.newteacher(
            Integer.parseInt(teachid.getText()),
            teachname.getText(),
            teachadd.getText(),
            teachdept.getText(),
            teachcontact.getText(),
            teachstatus.getText()
        );
        showRecords();
    }//GEN-LAST:event_saveBtnActionPerformed

    private void editBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editBtnMouseClicked

        Teachers c = new Teachers();

        c.edit_teacher(
            Integer.parseInt(teachid.getText()),
            teachname.getText(),
            teachadd.getText(),
            teachdept.getText(),
            teachcontact.getText(),
            teachstatus.getText()
        );
        showRecords();

    }//GEN-LAST:event_editBtnMouseClicked

    private void searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_searchMouseClicked

    private void assignTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_assignTableMouseClicked
        // TODO add your handling code here:
        int selectedRow = assignTable.getSelectedRow();

    if (selectedRow < 0) return;

    selectedAssignedSubjId = (String) assignTable.getValueAt(selectedRow, 0);
    }//GEN-LAST:event_assignTableMouseClicked

    private void teachTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teachTable2MouseClicked
        // TODO add your handling code here:                                        
    int selectedRow = teachTable2.getSelectedRow();

    if (selectedRow < 0) return;

    tid = (String) teachTable2.getValueAt(selectedRow, 0);
    teachid.setText(tid);

    tname = (String) teachTable2.getValueAt(selectedRow, 1);
    teachname.setText(tname);

    tadd = (String) teachTable2.getValueAt(selectedRow, 2);
    teachadd.setText(tadd);

    tdept = (String) teachTable2.getValueAt(selectedRow, 3);
    teachdept.setText(tdept);

    tcontact = (String) teachTable2.getValueAt(selectedRow, 4);
    teachcontact.setText(tcontact);

    tstatus = (String) teachTable2.getValueAt(selectedRow, 5);
    teachstatus.setText(tstatus);

    selectedAssignedSubjId = null;
    showAssignedSubjects(Integer.parseInt(tid));

    }//GEN-LAST:event_teachTable2MouseClicked

    private void AssignbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssignbuttonActionPerformed
        // TODO add your handling code here:
        if (tid == null || tid.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Select a teacher first.");
        return;
    }
    if (SubjectsForm.selectedSubjId == null || SubjectsForm.selectedSubjId.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Open the Subjects window and select a subject first.");
        return;
    }

    int confirm = javax.swing.JOptionPane.showConfirmDialog(
        this,
        "Assign Subject ID:" + SubjectsForm.selectedSubjId + " to Teacher ID:" + tid,
        "Confirm Assignment",
        javax.swing.JOptionPane.OK_CANCEL_OPTION,
        javax.swing.JOptionPane.QUESTION_MESSAGE
    );
    if (confirm != javax.swing.JOptionPane.OK_OPTION) {
        return;
    }

    Assign a = new Assign();
    boolean ok = a.assign_subject(Integer.parseInt(SubjectsForm.selectedSubjId), Integer.parseInt(tid));
    if (!ok) {
        javax.swing.JOptionPane.showMessageDialog(this, "That subject is already assigned to this teacher.");
    }
    showAssignedSubjects(Integer.parseInt(tid));
    }//GEN-LAST:event_AssignbuttonActionPerformed

    private void deletebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebuttonActionPerformed
        // TODO add your handling code here:
         if (tid == null || tid.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Select a teacher first.");
        return;
    }
    if (selectedAssignedSubjId == null || selectedAssignedSubjId.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Select a subject from the Assigned Subjects list first.");
        return;
    }

    int confirm = javax.swing.JOptionPane.showConfirmDialog(
        this,
        "Remove Subject ID:" + selectedAssignedSubjId + " from Teacher ID:" + tid,
        "Confirm Removal",
        javax.swing.JOptionPane.OK_CANCEL_OPTION,
        javax.swing.JOptionPane.QUESTION_MESSAGE
    );
    if (confirm != javax.swing.JOptionPane.OK_OPTION) {
        return;
    }

    Assign a = new Assign();
    a.delete_assignment(Integer.parseInt(selectedAssignedSubjId), Integer.parseInt(tid));
    selectedAssignedSubjId = null;
    showAssignedSubjects(Integer.parseInt(tid));
    }//GEN-LAST:event_deletebuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TeachersForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Assignbutton;
    private javax.swing.JTable assignTable;
    private javax.swing.JLabel assignlabelt;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton deletebutton;
    private javax.swing.JButton editBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextField search;
    private javax.swing.JTable teachTable;
    private javax.swing.JTable teachTable2;
    private javax.swing.JTextField teachadd;
    private javax.swing.JTextField teachcontact;
    private javax.swing.JTextField teachdept;
    private javax.swing.JTextField teachid;
    private javax.swing.JTextField teachname;
    private javax.swing.JTextField teachstatus;
    // End of variables declaration//GEN-END:variables
}
